name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
        - name: Clone-down test
          uses: actions/checkout@v3       
        - name: Build application
          run: chmod +x ci/build-app.sh && ci/build-app.sh
        - name: Test
          run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh